### ISSUE TITLE
pls fix

### ISSUE THREAD

**Issue by xXxNTMFCALLxXx** [DamourYouKnow/HAHA-NO-UR#1]
hey i'm not scouting the right cards please fix your scouting klab
Hey, je ne navigue pas sur les bonnes cartes, réparez votre klab scout
Hey no estoy explorando las tarjetas de la derecha por favor corrija su klab de exploración
이봐 요, 저는 올바른 카드를 스카우트하지 않고 있습니다. 정찰 klab을 수정하십시오.
ねえ、私はあなたのスカウトのklabを修正してください右のカードをスカウトしていないよ

**Comment by DamourYouKnow** [comment]
We apologize for any inconvenience this may have caused, and thank you for your understanding.
