### ISSUE TITLE
scout.py on line 204

### ISSUE THREAD

**Issue by MaT1g3R** [DamourYouKnow/HAHA-NO-UR#25]
```python
db = DatabaseController()
        if db.find_user(self._user) == None:
            db.insert_user(self._user)
        db.add_to_user_album(self._user, self._results)
```
Do you really want a new instance of DatabaseController for each scout? Seems more appropriate to use one instance for the whole bot.

**Comment by DamourYouKnow** [comment]
I was just running I quick test here. I'll change the Scout logic to return the cards list and handle the database updates in the scout commands module. The bot class will have an instance of DatabaseController.
